### PR TITLE
Change/more candle influecnes

### PR DESCRIPTION
**Pull request by GildedToxin**
Things seem fine? But id recommend testing this in case I missed anything

If this works well have to update the JEI stuff (if it doesnt automatically) , the QB, and the discord bot

### CODE REVIEW

**Review by Jonah-Hansen — APPROVED** [review]

**Comment by GildedToxin** [comment]
Did you also test these? Dont wanna merge until at least one other person has

**Comment by Jonah-Hansen** [comment]
> Did you also test these? Dont wanna merge until at least one other person has

no I haven't sorry

**Comment by GildedToxin** [comment]
You good, ill hold off for a bit then

**Comment by Jonah-Hansen** [comment]
tested boloks fury and torrent, both seem to work so I trust its all good!

**Pull request merged**
