### PR TITLE
Bug/broken beacons

### PR DESCRIPTION
**Pull request by GildedToxin**
will merge after villager trading one

### CODE REVIEW

**Review by Jonah-Hansen — APPROVED** [review]
either wait till #347 is merged or remove the orestages commit. always remember to branch off develop unless otherwise necessary!

**Comment by Jonah-Hansen** [comment]
could this also possibly be related to an issue with enlightened end that was fixed in version 5.0.12 (we are on 5.0.11)

image

**Comment by Jonah-Hansen** [comment]
did you upload modlist and manifest to wrong branch? also the only difference seems to re add goal optimizer which is supposed to be removed

use this to compare the modlists as it lets you sort the lines 
https://diffsort.com/

**Comment by GildedToxin** [comment]
pfft yes I did
im so dumb lol
ty!

**Comment by GildedToxin** [comment]
Is there a good way to undo a commit?

**Comment by Jonah-Hansen** [comment]
> Is there a good way to undo a commit?

https://stackoverflow.com/questions/22682870/how-can-i-undo-pushed-commits-using-git

`git revert head` should work
if not `git revert head~1`

**Pull request merged**
