### PR TITLE
fix yosby default options

### LINKED ISSUE #287: default options from yosby dont apply
yosby mod default options preset is not properly applying.

### PR DESCRIPTION
**Pull request by Jonah-Hansen**
closes #287 
I guess it was just some wrong formatting on a couple of them causing the whole thing to fail? idk I just manually set all the options in game. tested by making a fresh instance with these and it worked.

### CODE REVIEW

**Comment by GildedToxin** [comment]
The `none` insteand of `unknown` really got us in the end
are these the settings that are planned for 1.5.4 or are we gonna have to go back through them?

**Comment by GildedToxin** [comment]
ill test tomorrow and then approve (:

**Comment by Jonah-Hansen** [comment]
these are what was originally in yosby, just had to go through one by one and set them in game.
so yes these are the settings for 1.5.4

**Review by GildedToxin — APPROVED** [review]
Looks good!

**Review by RUsami — APPROVED** [review]

**Pull request merged**
