### PR TITLE
add waystone variants and .withoutTag() to rangs

### LINKED ISSUE #200: dont break waystones with pickarang
pickarang can break waystones, including naturally spawned ones and drop the item

### PR DESCRIPTION
**Pull request by Jonah-Hansen**
closes #200 
again

### CODE REVIEW

**Comment by Jonah-Hansen** [comment]
@GildedToxin review plssss

**Comment by GildedToxin** [comment]
Sorry missed this!

**Review by GildedToxin — APPROVED** [review]
You could always just make a waystones tag in `tag_manager.zs` 
Honestly not that big of a deal if you dont
Either way looks good!

**Comment by Jonah-Hansen** [comment]
> You could always just make a waystones tag in `tag_manager.zs` Honestly not that big of a deal if you dont Either way looks good!

true but meh

**Pull request merged**
