### PR TITLE
remove voidfog mod

### LINKED ISSUE #246: remove void fog mod

### PR DESCRIPTION
**Pull request by Jonah-Hansen**
closes #246 at @RUsami 's request

### CODE REVIEW

**Comment by Jonah-Hansen** [comment]
Reminder for everyone.. this just removes it from git, anytime someone else adds or removes a mod you will have to manually add it or remove it from your instance

**Comment by GildedToxin** [comment]
So when this gets merged in ill have to remove the mod from my personal mod list?

**Review by GildedToxin — APPROVED** [review]

**Comment by Jonah-Hansen** [comment]
> So when this gets merged in ill have to remove the mod from my personal mod list?

yes that's the easiest way. otherwise you have to export your profile, unzip, replace manifest and modlist with the ones from repo, rezip, and import profile to sync up if there were major changes

**Review by Huskykyle — APPROVED** [review]

**Review by RUsami — COMMENTED** [review]
Review review

**Pull request merged**
