### PR TITLE
add bash script to copy contents of overrides folder to mc instance

### PR DESCRIPTION
**Pull request by Jonah-Hansen**
### note: this procedure is optional. it only provides coding qualify of life for those familiar with git 

1. edit `copyToInstance.sh.example` and set 'path' to the path to your dev instance.
2. rename the script to remove `.example`
3. run the script with 
```bash
bash copyToInstance.sh
```
to copy all files from /overrides to your instance folder.

this allows you to modify the files in the git repo and then push them to your instance which allows for git tracking while you work!

if using vscode, install the recommended extension [run it on](https://marketplace.visualstudio.com/items?itemName=fsevenm.run-it-on) to automatically apply changes on save. 

if on windows, I recommend installing [gitbash](https://git-scm.com/downloads) if you don't have it yet, as Windows cant natively run bash scripts and trying to write a .bat file was giving me a headache

### CODE REVIEW

**Comment by Jonah-Hansen** [comment]
@ISOUL22 @GildedToxin did you guys get a chance to look at this? if you like it I'll merge it in and you can start using it if you want

**Comment by GildedToxin** [comment]
I assume all we have to do is open up vs code with the file path being where the `.vscode.settings` is?

**Comment by Jonah-Hansen** [comment]
> I assume all we have to do is open up vs code with the file path being where the `.vscode.settings` is?

yeah basically with this you can open the repo folder with vscode and make your changes there which lets you see which lines were modified right away, then run the script and it will copy the contents of /overrides to your instance.

install the extension to enable automatic copying when a file is edited and saved. 

not sure if the script changes will take effect immediately or if it will require a reload.

**Review by GildedToxin — APPROVED** [review]
Looks good!

**Pull request merged**
