### PR TITLE
removed tempest pearl from scallop loot pool

### LINKED ISSUE #152: Remove Tempest Pearl from those clam dudes' loot pools
They don't deserve it

### PR DESCRIPTION
**Pull request by GildedToxin**
closes #152

### CODE REVIEW

**Comment by iakfar** [comment]
gonna miss that since pearls are so unpleasant to get

**Comment by GildedToxin** [comment]
I plan to add a crushing recipe for the clams to make them more consistent prob a low drop chance though for balance sake

**Comment by iakfar** [comment]
yeah that works much better

**Comment by Jonah-Hansen** [comment]
do we need to update the quest book at all for this change?

**Comment by GildedToxin** [comment]
Nope!
image
image

**Review by Jonah-Hansen — APPROVED** [review]

**Pull request merged**
