### PR TITLE
Fixed bag of horrors

### PR DESCRIPTION
**Pull request by GildedToxin**

### CODE REVIEW

**Review by Jonah-Hansen — APPROVED** [review]

**Comment by Jonah-Hansen** [comment]
just realized this merged to main. you should open a pr to merge main to develop. main should never be ahead of develop besides merge commits

**Comment by GildedToxin** [comment]
How do I undo it?

**Comment by GildedToxin** [comment]
image
this?

**Comment by Jonah-Hansen** [comment]
yeah, then reopen the pr to develop

**Pull request merged**
